backend:
  name: git-gateway
  branch: master
    # name: github
    # branch: master
    # repo: deathtothecorporation/jekyll-blog

media_folder: "assets/images"
public_folder: "_site"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Written Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
        # - { label: "Authors", name: "authors", widget: "list", default: ["cve"] }
      - { label: "Tags", name: "tags", widget: "list", default: ["written"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Short Description", name: "description", widget: "string", default: "Provide a short description which will be used on social share cards" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Visible?", name: "visible", widget: "boolean", default: false }
      - {
          label: 'Authors',
          name: 'authors',
          widget: 'relation',
          collection: 'authors',
          multiple: true,
          display_fields: [name],
          search_fields: [name],
          value_field: 'identifier',
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "podcasts"
    label: "Podcasts"
    folder: "_podcasts"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "podcast" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["podcast"] }
      - { label: "Air Date", name: "date", widget: "datetime" }
      - { label: "Short Description", name: "description", widget: "string", default: "Provide a short description which will be used on social share cards" }
      - { label: "Episode Art (square please)", name: "image", widget: "image" }
      - { label: "Visible?", name: "visible", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Initials', name: 'identifier', widget: 'string' }
      - { label: 'Display Name', name: 'name', widget: 'string' }
      - { label: 'Avatar', name: 'avatar', widget: 'string' }
      - { label: 'Email (optional)', name: 'email', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
